/* eslint-disable @typescript-eslint/no-explicit-any */
import { join } from 'path';
import { merge } from 'lodash';
import devConfig from './config.dev';
import testConfig from './config.test';
import preConfig from './config.prev';
import productionConfig from './config.production';

let config: Record<string, any> = {};
switch (process.env.LAUNCH_ENV) {
  case 'development':
    config = devConfig();
    break;
  case 'test':
    config = testConfig();
    break;
  case 'pre-production':
    config = preConfig();
    break;
  case 'production':
    config = productionConfig();
    break;
}

export default (): Record<string, any> => {
  const projectPath = process.cwd();
  const defaultConfig = {
    logger: {
      // Refer to 'https://github.com/winstonjs/winston' for more options
      level: 'info',
      defaultMeta: { application: 'node-nestjs' },
      exitOnError: false,
      file: {
        // Refer to 'https://github.com/winstonjs/winston-daily-rotate-file#options' for more options
        filename: 'app-%DATE%.log',
        datePattern: 'YYYY-MM-DD',
        dirname: join(projectPath, 'logs')
      }
    },
    port: parseInt(process.env.PORT || '3000', 10),
    db: {
      // Refer to 'https://typeorm.io/#/mongodb' for more options
      type: 'mongodb',
      host: process.env.DATABASE_HOST || 'localhost',
      port: parseInt(process.env.DATABASE_PORT || '27017', 10),
      username: 'ndUser',
      password: '123456',
      database: 'db_net_disk',
      synchronize: true,
      logging: true
    },
    jwt: {
      // generated by 'http://travistidwell.com/jsencrypt/demo/'
      publicKey: `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQD0WB2QOJQq93uh6Nq22pDbTnqz
Bi2Eda61Gg+uV7ugAqxcMA3OOWbDGPsHD/LMgqSjWOKDw7lMDMVk2xCL+tQWDQXc
xFnMejreWpsdR2mDkyMpVlzUXxr8D/4jhk0HEiZ3UnyGXBdpp6W1DwuqAb4K3W3S
PXe4akeKJ6cdj1kEuwIDAQAB
-----END PUBLIC KEY-----`,
      privateKey: `-----BEGIN RSA PRIVATE KEY-----
MIICXwIBAAKBgQD0WB2QOJQq93uh6Nq22pDbTnqzBi2Eda61Gg+uV7ugAqxcMA3O
OWbDGPsHD/LMgqSjWOKDw7lMDMVk2xCL+tQWDQXcxFnMejreWpsdR2mDkyMpVlzU
Xxr8D/4jhk0HEiZ3UnyGXBdpp6W1DwuqAb4K3W3SPXe4akeKJ6cdj1kEuwIDAQAB
AoGBAM5zCP+LHn2zPw2NHgbzYwM5KujKJnlNqYCw9WDcFdZbi+AUZgXBcDcVizvr
WL09APhXKIQmQhCklb/ia/epxbj5LmrU//rT71889fitjlh4PkjLnng6Mus8jfbb
eUBrsdUUQdf8sJdH1RVleLRbpoAq0fmleqwO5r+Opo97IKLRAkEA/vWuxtfT2WqV
2cUjBkNslGJYbcMHYspSz7MmMhbL7gVIvPNiJ/FvBFu7XwHY1NgUuQOoVjvdsdIS
TemEAHy8IwJBAPVXWCk9RXh8DW+SZuuQbFFqwCLXr/6/B1EpepCHteySUTA0d268
QrrdlWO6O/gvcFAvuXEn8JcYHCSgZP+YsokCQQD7tRe4rYkz4ztPxIVAgL4ofDMr
Idkf2fkJnqc92i24rjTSfkHQh1X/6oRAVrV35GAJDChcAjxreqahjsHILV0bAkEA
gRTYdLIhB/g01XvwnIXbB6cjufFDTsPRJLmvG7XbWMHO547jO6bfcRO+Ur8caEMF
U5sYdVmvMr/jpr2hBf2gCQJBANfmQV3YccP9zCB3DKCmfSD1i1Dzc/1iUtks/IvT
ZUNeSf0exCHgGuO0hLzdUoVxOzVGKhf+usAZq9eMJpMm/GQ=
-----END RSA PRIVATE KEY-----`,
      signOptions: {
        // Refer to 'https://github.com/auth0/node-jsonwebtoken#usage' for more options
        expiresIn: '24h',
        // If we decide to use asymmetric algorithms, be sure you pass the 'algorithm' option.
        algorithm: 'RS256'
      }
    },
    uploadOption: {
      limits: {
        // Refer to 'https://github.com/expressjs/multer#limits' for more options
        fileSize: 6 * 1024 * 1024
      },
      segmentDir: join(projectPath, 'upload', 'segments'),
      fileDir: join(projectPath, 'upload', 'files')
    }
  };
  return merge(defaultConfig, config);
};
